### ISSUE TITLE
help

### ISSUE THREAD

**Issue by yanghuajian** [seathiefwang/FaceRecognition-tensorflow#17]
运行is_myface:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Facerecognition (1)\is_my_face.py", line 135, in <module>
    saver.restore(sess, tf.train.latest_checkpoint('.'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1796, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

**Comment by FengGuanxi** [comment]
I met the same question.

**Comment by Shazuka** [comment]
Need help with the same problem...

**Comment by huitang** [comment]
same problem

**Comment by Flyinheaven** [comment]
I met the same question,have you solved it?
